data:
  root: /path/to/ABC
  split: train
  layout: abc
  step_root: /path/to/ABC/chunks
  graph_root: /path/to/ABC_graphs
  uvnet_root: external/uvnet
model:
  mask_ratio: 0.6
  embedding_dim: 64
loss:
  lambda_geom: 0.2
  lambda_face: 0.2
train:
  epochs: 1
  batch_size: 1
  device: cpu
